# ===================================================================
# Bachelor's Project Quarto Configuration
# ===================================================================

# -- UNIVERSAL SETTINGS --
author:
  - name: Frederik Bender BÃ¸eck-Nielsen
    email: lzq867@alumni.ku.dk
    affiliation:
    - name: Department of Political Science - University of Copenhagen
date: last-modified
date-format: D. MMMM, YYYY
lang: da

# -- REFERENCES --
bibliography: references.bib
csl: chicago-author-date.csl
citeproc: true
link-citations: true

# -- TABLE OF CONTENTS --
toc: true
toc-depth: 3
toc-title: Contents
toc-indent: 1.6em

# -- SECTIONS --
number-sections: true
number-depth: 3


# -- PAGE LAYOUT --
papersize: a4
justify: true
hyphenate: true
linestretch: 1.45

# -- CHUNK OPTIONS --
execute:
  echo: false
  message: false
  warning: false
  include: true

# -- FIG OPTIONS --
knitr:
  opts_chunk:
    dev: "svglite"
    fig-width: 15
    fig-asp: 0.77
    tbl-cap-location: bottom

# -- Typst Settings --
format:
  typst:
    template-partials:
    - ../definitions.typ
    font-paths: ../fonts/
    columns: 1
    margin:
      top: 3cm
      bottom: 3.5cm
      x: 3cm
    fontsize: 11pt
    section-numbering: 1.1.1.
    include-in-header:
      - text: |
          #show link: set text(fill: rgb(0, 0, 255))
          #show ref: set text(fill: rgb(0, 0, 255))
