# ===================================================================
# Bachelor's Project Quarto Configuration
# ===================================================================

# -- UNIVERSAL SETTINGS --
lang: da

# -- REFERENCES --
bibliography: references.bib
csl: chicago-author-date.csl
citeproc: true
link-citations: true

# -- TABLE OF CONTENTS --
toc: false

# -- SECTIONS --
number-sections: true
number-depth: 3


# -- PAGE LAYOUT --
papersize: a4
justify: true
hyphenate: true

# -- CHUNK OPTIONS --
execute:
  echo: false
  message: false
  warning: false
  include: true

# -- FIG OPTIONS --
knitr:
  opts_chunk:
    dev: "svglite"
    fig-width: 15
    fig-asp: 0.77
    tbl-cap-location: bottom

# -- Typst Settings --
format:
  typst:
    template-partials:
    - ../definitions.typ
    font-paths: ../fonts/
    columns: 1
    margin:
      top: 3cm
      bottom: 3.5cm
      x: 3cm
    fontsize: 11pt
    section-numbering: 1.1.1.
    include-in-header:
      - text: |
          #set par(leading: 0.75em, spacing: 1.5em)
          #show link: set text(fill: rgb(0, 0, 255))
          #show ref: set text(fill: rgb(0, 0, 255))
